In [8]:
import pandas as pd

In [9]:
data = pd.read_csv('drom.csv', ',')
data

/Users/user/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3369: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,Стоимость,Модель,Год выпуска,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач
0,0,86 ₽,Cobra Crossfire,2013,Уфа,10 км,150 куб. см.,бензин,карбюратор,4-тактный,механика
1,1,6000 ₽,Урал ИМЗ 8.103-10,1991,Пограничный,10 км,499 куб. см.,бензин,-,4-тактный,-
2,2,6500 ₽,Днепр 16М,1985,Барабинск,-,450 куб. см.,-,карбюратор,-,механика
3,3,8000 ₽,Восход Восход,1981,Кызыл,-,175 куб. см.,-,-,-,-
4,4,9999 ₽,Honda CBR 919RR,1999,Спасск-Дальний,50 000 км,919 куб. см.,бензин,-,4-тактный,-
...,...,...,...,...,...,...,...,...,...,...,...
15453,15453,8100000 ₽,Harley-Davidson CVO Street Glide,2024,Новосибирск,-,1977 куб. см.,бензин,-,4-тактный,-
15454,15454,8250000 ₽,Harley-Davidson CVO Road Glide,2025,Новосибирск,-,1977 куб. см.,бензин,инжектор,4-тактный,механика
15455,15455,8500000 ₽,Harley-Davidson CVO Road Glide,2023,Новосибирск,-,1923 куб. см.,бензин,-,4-тактный,-
15456,15456,8500000 ₽,Harley-Davidson CVO Road Glide,2023,Красноярск,-,1923 куб. см.,бензин,инжектор,4-тактный,механика
15457,15457,10500000 ₽,Ducati Diavel,2024,Москва,-,1158 куб. см.,бензин,инжектор,4-тактный,механика

In [10]:
del data['Unnamed: 0']

In [11]:
data

,Стоимость,Модель,Год выпуска,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач
0,86 ₽,Cobra Crossfire,2013,Уфа,10 км,150 куб. см.,бензин,карбюратор,4-тактный,механика
1,6000 ₽,Урал ИМЗ 8.103-10,1991,Пограничный,10 км,499 куб. см.,бензин,-,4-тактный,-
2,6500 ₽,Днепр 16М,1985,Барабинск,-,450 куб. см.,-,карбюратор,-,механика
3,8000 ₽,Восход Восход,1981,Кызыл,-,175 куб. см.,-,-,-,-
4,9999 ₽,Honda CBR 919RR,1999,Спасск-Дальний,50 000 км,919 куб. см.,бензин,-,4-тактный,-
...,...,...,...,...,...,...,...,...,...,...
15453,8100000 ₽,Harley-Davidson CVO Street Glide,2024,Новосибирск,-,1977 куб. см.,бензин,-,4-тактный,-
15454,8250000 ₽,Harley-Davidson CVO Road Glide,2025,Новосибирск,-,1977 куб. см.,бензин,инжектор,4-тактный,механика
15455,8500000 ₽,Harley-Davidson CVO Road Glide,2023,Новосибирск,-,1923 куб. см.,бензин,-,4-тактный,-
15456,8500000 ₽,Harley-Davidson CVO Road Glide,2023,Красноярск,-,1923 куб. см.,бензин,инжектор,4-тактный,механика
15457,10500000 ₽,Ducati Diavel,2024,Москва,-,1158 куб. см.,бензин,инжектор,4-тактный,механика

In [28]:
for i in range(len(data)):
    data['Стоимость'][i] = int(data['Стоимость'][i][:-2])
    data['Год выпуска'][i] = int(data['Год выпуска'][i])
    data['Объём двигателся'][i] = int(data['Объём двигателся'][i][:-9])

    if 'км' in data['Пробег'][i]:
        data['Пробег'][i] = int(data['Пробег'][i][:-3])
    elif data['Год выпуска'][i] > 2018:
        data['Пробег'][i] = 0
    
    if data['Тактность'][i] != '-':
        data['Тактность'][i] = int(data['Тактность'][i][:-8])

TypeError: 'int' object is not subscriptable

In [29]:
int(data['Стоимость'][1][:-2])

6000