In [96]:
import pandas as pd

df = pd.read_csv("drom.csv")

df

,Unnamed: 0,Стоимость,Модель,Год выпуска,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач
0,0,86 ₽,Cobra Crossfire,2013,Уфа,10 км,150 куб. см.,бензин,карбюратор,4-тактный,механика
1,1,6000 ₽,Урал ИМЗ 8.103-10,1991,Пограничный,10 км,499 куб. см.,бензин,-,4-тактный,-
2,2,6500 ₽,Днепр 16М,1985,Барабинск,-,450 куб. см.,-,карбюратор,-,механика
3,3,8000 ₽,Восход Восход,1981,Кызыл,-,175 куб. см.,-,-,-,-
4,4,9999 ₽,Honda CBR 919RR,1999,Спасск-Дальний,50 000 км,919 куб. см.,бензин,-,4-тактный,-
...,...,...,...,...,...,...,...,...,...,...,...
15453,15453,8100000 ₽,Harley-Davidson CVO Street Glide,2024,Новосибирск,-,1977 куб. см.,бензин,-,4-тактный,-
15454,15454,8250000 ₽,Harley-Davidson CVO Road Glide,2025,Новосибирск,-,1977 куб. см.,бензин,инжектор,4-тактный,механика
15455,15455,8500000 ₽,Harley-Davidson CVO Road Glide,2023,Новосибирск,-,1923 куб. см.,бензин,-,4-тактный,-
15456,15456,8500000 ₽,Harley-Davidson CVO Road Glide,2023,Красноярск,-,1923 куб. см.,бензин,инжектор,4-тактный,механика
15457,15457,10500000 ₽,Ducati Diavel,2024,Москва,-,1158 куб. см.,бензин,инжектор,4-тактный,механика

In [97]:
if 'Unnamed: 0' in df.columns:
    df.drop(columns=['Unnamed: 0'], inplace=True)

df

,Стоимость,Модель,Год выпуска,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач
0,86 ₽,Cobra Crossfire,2013,Уфа,10 км,150 куб. см.,бензин,карбюратор,4-тактный,механика
1,6000 ₽,Урал ИМЗ 8.103-10,1991,Пограничный,10 км,499 куб. см.,бензин,-,4-тактный,-
2,6500 ₽,Днепр 16М,1985,Барабинск,-,450 куб. см.,-,карбюратор,-,механика
3,8000 ₽,Восход Восход,1981,Кызыл,-,175 куб. см.,-,-,-,-
4,9999 ₽,Honda CBR 919RR,1999,Спасск-Дальний,50 000 км,919 куб. см.,бензин,-,4-тактный,-
...,...,...,...,...,...,...,...,...,...,...
15453,8100000 ₽,Harley-Davidson CVO Street Glide,2024,Новосибирск,-,1977 куб. см.,бензин,-,4-тактный,-
15454,8250000 ₽,Harley-Davidson CVO Road Glide,2025,Новосибирск,-,1977 куб. см.,бензин,инжектор,4-тактный,механика
15455,8500000 ₽,Harley-Davidson CVO Road Glide,2023,Новосибирск,-,1923 куб. см.,бензин,-,4-тактный,-
15456,8500000 ₽,Harley-Davidson CVO Road Glide,2023,Красноярск,-,1923 куб. см.,бензин,инжектор,4-тактный,механика
15457,10500000 ₽,Ducati Diavel,2024,Москва,-,1158 куб. см.,бензин,инжектор,4-тактный,механика

In [98]:
df['Стоимость'] = (
    df['Стоимость']
    .str.replace('₽', '', regex=False)
    .str.replace(' ', '', regex=False)
    .astype(int)
)

df

,Стоимость,Модель,Год выпуска,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач
0,86,Cobra Crossfire,2013,Уфа,10 км,150 куб. см.,бензин,карбюратор,4-тактный,механика
1,6000,Урал ИМЗ 8.103-10,1991,Пограничный,10 км,499 куб. см.,бензин,-,4-тактный,-
2,6500,Днепр 16М,1985,Барабинск,-,450 куб. см.,-,карбюратор,-,механика
3,8000,Восход Восход,1981,Кызыл,-,175 куб. см.,-,-,-,-
4,9999,Honda CBR 919RR,1999,Спасск-Дальний,50 000 км,919 куб. см.,бензин,-,4-тактный,-
...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,2024,Новосибирск,-,1977 куб. см.,бензин,-,4-тактный,-
15454,8250000,Harley-Davidson CVO Road Glide,2025,Новосибирск,-,1977 куб. см.,бензин,инжектор,4-тактный,механика
15455,8500000,Harley-Davidson CVO Road Glide,2023,Новосибирск,-,1923 куб. см.,бензин,-,4-тактный,-
15456,8500000,Harley-Davidson CVO Road Glide,2023,Красноярск,-,1923 куб. см.,бензин,инжектор,4-тактный,механика
15457,10500000,Ducati Diavel,2024,Москва,-,1158 куб. см.,бензин,инжектор,4-тактный,механика

In [99]:
df['Год выпуска'] = pd.to_numeric(df['Год выпуска'], errors='coerce').astype('Int64')

df

,Стоимость,Модель,Год выпуска,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач
0,86,Cobra Crossfire,2013,Уфа,10 км,150 куб. см.,бензин,карбюратор,4-тактный,механика
1,6000,Урал ИМЗ 8.103-10,1991,Пограничный,10 км,499 куб. см.,бензин,-,4-тактный,-
2,6500,Днепр 16М,1985,Барабинск,-,450 куб. см.,-,карбюратор,-,механика
3,8000,Восход Восход,1981,Кызыл,-,175 куб. см.,-,-,-,-
4,9999,Honda CBR 919RR,1999,Спасск-Дальний,50 000 км,919 куб. см.,бензин,-,4-тактный,-
...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,2024,Новосибирск,-,1977 куб. см.,бензин,-,4-тактный,-
15454,8250000,Harley-Davidson CVO Road Glide,2025,Новосибирск,-,1977 куб. см.,бензин,инжектор,4-тактный,механика
15455,8500000,Harley-Davidson CVO Road Glide,2023,Новосибирск,-,1923 куб. см.,бензин,-,4-тактный,-
15456,8500000,Harley-Davidson CVO Road Glide,2023,Красноярск,-,1923 куб. см.,бензин,инжектор,4-тактный,механика
15457,10500000,Ducati Diavel,2024,Москва,-,1158 куб. см.,бензин,инжектор,4-тактный,механика

In [100]:
import numpy as np

df['Пробег'] = df['Пробег'].str.replace(' км', '', regex=False).str.replace(' ', '', regex=False)

mask_2020_plus = (df['Год выпуска'].notna()) & (df['Год выпуска'] >= 2020)
mask_2019_or_missing = ~mask_2020_plus

df.loc[mask_2020_plus & (df['Пробег'] == '-'), 'Пробег'] = '0'
df.loc[mask_2019_or_missing & (df['Пробег'] == '-'), 'Пробег'] = np.nan

df['Пробег'] = pd.to_numeric(df['Пробег'], errors='coerce')

df

,Стоимость,Модель,Год выпуска,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач
0,86,Cobra Crossfire,2013,Уфа,10.0,150 куб. см.,бензин,карбюратор,4-тактный,механика
1,6000,Урал ИМЗ 8.103-10,1991,Пограничный,10.0,499 куб. см.,бензин,-,4-тактный,-
2,6500,Днепр 16М,1985,Барабинск,NaN,450 куб. см.,-,карбюратор,-,механика
3,8000,Восход Восход,1981,Кызыл,NaN,175 куб. см.,-,-,-,-
4,9999,Honda CBR 919RR,1999,Спасск-Дальний,50000.0,919 куб. см.,бензин,-,4-тактный,-
...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,2024,Новосибирск,0.0,1977 куб. см.,бензин,-,4-тактный,-
15454,8250000,Harley-Davidson CVO Road Glide,2025,Новосибирск,0.0,1977 куб. см.,бензин,инжектор,4-тактный,механика
15455,8500000,Harley-Davidson CVO Road Glide,2023,Новосибирск,0.0,1923 куб. см.,бензин,-,4-тактный,-
15456,8500000,Harley-Davidson CVO Road Glide,2023,Красноярск,0.0,1923 куб. см.,бензин,инжектор,4-тактный,механика
15457,10500000,Ducati Diavel,2024,Москва,0.0,1158 куб. см.,бензин,инжектор,4-тактный,механика

In [101]:
df['Объём двигателя'] = df['Объём двигателя'].astype(str)

df['Объём двигателя'] = (
    df['Объём двигателя']
    .str.replace('куб. см.', '', regex=False)
    .str.replace(' ', '', regex=False)
)

df['Объём двигателя'] = pd.to_numeric(df['Объём двигателя'], errors='coerce').astype('Int64')

df

,Стоимость,Модель,Год выпуска,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач
0,86,Cobra Crossfire,2013,Уфа,10.0,150,бензин,карбюратор,4-тактный,механика
1,6000,Урал ИМЗ 8.103-10,1991,Пограничный,10.0,499,бензин,-,4-тактный,-
2,6500,Днепр 16М,1985,Барабинск,NaN,450,-,карбюратор,-,механика
3,8000,Восход Восход,1981,Кызыл,NaN,175,-,-,-,-
4,9999,Honda CBR 919RR,1999,Спасск-Дальний,50000.0,919,бензин,-,4-тактный,-
...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,2024,Новосибирск,0.0,1977,бензин,-,4-тактный,-
15454,8250000,Harley-Davidson CVO Road Glide,2025,Новосибирск,0.0,1977,бензин,инжектор,4-тактный,механика
15455,8500000,Harley-Davidson CVO Road Glide,2023,Новосибирск,0.0,1923,бензин,-,4-тактный,-
15456,8500000,Harley-Davidson CVO Road Glide,2023,Красноярск,0.0,1923,бензин,инжектор,4-тактный,механика
15457,10500000,Ducati Diavel,2024,Москва,0.0,1158,бензин,инжектор,4-тактный,механика

In [102]:
cols_to_clean = ['Тип топлива', 'Тип подачи топлива', 'Коробка передач', 'Тактность']

df[cols_to_clean] = df[cols_to_clean].replace("-", np.nan)

df['Объём двигателя'] = df['Объём двигателя'].replace("-", np.nan)

for col in cols_to_clean:
    df[col] = df[col].astype('category')

df

,Стоимость,Модель,Год выпуска,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач
0,86,Cobra Crossfire,2013,Уфа,10.0,150,бензин,карбюратор,4-тактный,механика
1,6000,Урал ИМЗ 8.103-10,1991,Пограничный,10.0,499,бензин,NaN,4-тактный,NaN
2,6500,Днепр 16М,1985,Барабинск,NaN,450,NaN,карбюратор,NaN,механика
3,8000,Восход Восход,1981,Кызыл,NaN,175,NaN,NaN,NaN,NaN
4,9999,Honda CBR 919RR,1999,Спасск-Дальний,50000.0,919,бензин,NaN,4-тактный,NaN
...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,2024,Новосибирск,0.0,1977,бензин,NaN,4-тактный,NaN
15454,8250000,Harley-Davidson CVO Road Glide,2025,Новосибирск,0.0,1977,бензин,инжектор,4-тактный,механика
15455,8500000,Harley-Davidson CVO Road Glide,2023,Новосибирск,0.0,1923,бензин,NaN,4-тактный,NaN
15456,8500000,Harley-Davidson CVO Road Glide,2023,Красноярск,0.0,1923,бензин,инжектор,4-тактный,механика
15457,10500000,Ducati Diavel,2024,Москва,0.0,1158,бензин,инжектор,4-тактный,механика

In [103]:
df['Возраст мотоцикла'] = 2025 - df['Год выпуска']

df

,Стоимость,Модель,Год выпуска,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач,Возраст мотоцикла
0,86,Cobra Crossfire,2013,Уфа,10.0,150,бензин,карбюратор,4-тактный,механика,12
1,6000,Урал ИМЗ 8.103-10,1991,Пограничный,10.0,499,бензин,NaN,4-тактный,NaN,34
2,6500,Днепр 16М,1985,Барабинск,NaN,450,NaN,карбюратор,NaN,механика,40
3,8000,Восход Восход,1981,Кызыл,NaN,175,NaN,NaN,NaN,NaN,44
4,9999,Honda CBR 919RR,1999,Спасск-Дальний,50000.0,919,бензин,NaN,4-тактный,NaN,26
...,...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,2024,Новосибирск,0.0,1977,бензин,NaN,4-тактный,NaN,1
15454,8250000,Harley-Davidson CVO Road Glide,2025,Новосибирск,0.0,1977,бензин,инжектор,4-тактный,механика,0
15455,8500000,Harley-Davidson CVO Road Glide,2023,Новосибирск,0.0,1923,бензин,NaN,4-тактный,NaN,2
15456,8500000,Harley-Davidson CVO Road Glide,2023,Красноярск,0.0,1923,бензин,инжектор,4-тактный,механика,2
15457,10500000,Ducati Diavel,2024,Москва,0.0,1158,бензин,инжектор,4-тактный,механика,1

In [104]:
df.drop(columns=['Год выпуска'], inplace=True)

df

,Стоимость,Модель,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач,Возраст мотоцикла
0,86,Cobra Crossfire,Уфа,10.0,150,бензин,карбюратор,4-тактный,механика,12
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,бензин,NaN,4-тактный,NaN,34
2,6500,Днепр 16М,Барабинск,NaN,450,NaN,карбюратор,NaN,механика,40
3,8000,Восход Восход,Кызыл,NaN,175,NaN,NaN,NaN,NaN,44
4,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,бензин,NaN,4-тактный,NaN,26
...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,бензин,NaN,4-тактный,NaN,1
15454,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,бензин,инжектор,4-тактный,механика,0
15455,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,бензин,NaN,4-тактный,NaN,2
15456,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,бензин,инжектор,4-тактный,механика,2
15457,10500000,Ducati Diavel,Москва,0.0,1158,бензин,инжектор,4-тактный,механика,1

In [105]:
df['Коробка (код)'] = df['Коробка передач'].map({
    'механика': 0,
    'автомат': 1
})

df

,Стоимость,Модель,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Коробка передач,Возраст мотоцикла,Коробка (код)
0,86,Cobra Crossfire,Уфа,10.0,150,бензин,карбюратор,4-тактный,механика,12,0
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,бензин,NaN,4-тактный,NaN,34,NaN
2,6500,Днепр 16М,Барабинск,NaN,450,NaN,карбюратор,NaN,механика,40,0
3,8000,Восход Восход,Кызыл,NaN,175,NaN,NaN,NaN,NaN,44,NaN
4,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,бензин,NaN,4-тактный,NaN,26,NaN
...,...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,бензин,NaN,4-тактный,NaN,1,NaN
15454,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,бензин,инжектор,4-тактный,механика,0,0
15455,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,бензин,NaN,4-тактный,NaN,2,NaN
15456,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,бензин,инжектор,4-тактный,механика,2,0
15457,10500000,Ducati Diavel,Москва,0.0,1158,бензин,инжектор,4-тактный,механика,1,0

In [106]:
df.drop(columns=['Коробка передач'], inplace=True)

df

,Стоимость,Модель,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Возраст мотоцикла,Коробка (код)
0,86,Cobra Crossfire,Уфа,10.0,150,бензин,карбюратор,4-тактный,12,0
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,бензин,NaN,4-тактный,34,NaN
2,6500,Днепр 16М,Барабинск,NaN,450,NaN,карбюратор,NaN,40,0
3,8000,Восход Восход,Кызыл,NaN,175,NaN,NaN,NaN,44,NaN
4,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,бензин,NaN,4-тактный,26,NaN
...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,бензин,NaN,4-тактный,1,NaN
15454,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,бензин,инжектор,4-тактный,0,0
15455,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,бензин,NaN,4-тактный,2,NaN
15456,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,бензин,инжектор,4-тактный,2,0
15457,10500000,Ducati Diavel,Москва,0.0,1158,бензин,инжектор,4-тактный,1,0

In [107]:
df['Тактность (код)'] = df['Тактность'].map({
    '2-тактный': 0,
    '4-тактный': 1
})

df

,Стоимость,Модель,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Тактность,Возраст мотоцикла,Коробка (код),Тактность (код)
0,86,Cobra Crossfire,Уфа,10.0,150,бензин,карбюратор,4-тактный,12,0,1
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,бензин,NaN,4-тактный,34,NaN,1
2,6500,Днепр 16М,Барабинск,NaN,450,NaN,карбюратор,NaN,40,0,NaN
3,8000,Восход Восход,Кызыл,NaN,175,NaN,NaN,NaN,44,NaN,NaN
4,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,бензин,NaN,4-тактный,26,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,бензин,NaN,4-тактный,1,NaN,1
15454,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,бензин,инжектор,4-тактный,0,0,1
15455,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,бензин,NaN,4-тактный,2,NaN,1
15456,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,бензин,инжектор,4-тактный,2,0,1
15457,10500000,Ducati Diavel,Москва,0.0,1158,бензин,инжектор,4-тактный,1,0,1

In [108]:
df.drop(columns=['Тактность'], inplace=True)

df

,Стоимость,Модель,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Возраст мотоцикла,Коробка (код),Тактность (код)
0,86,Cobra Crossfire,Уфа,10.0,150,бензин,карбюратор,12,0,1
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,бензин,NaN,34,NaN,1
2,6500,Днепр 16М,Барабинск,NaN,450,NaN,карбюратор,40,0,NaN
3,8000,Восход Восход,Кызыл,NaN,175,NaN,NaN,44,NaN,NaN
4,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,бензин,NaN,26,NaN,1
...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,бензин,NaN,1,NaN,1
15454,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,бензин,инжектор,0,0,1
15455,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,бензин,NaN,2,NaN,1
15456,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,бензин,инжектор,2,0,1
15457,10500000,Ducati Diavel,Москва,0.0,1158,бензин,инжектор,1,0,1

In [109]:
df['Подача топлива (код)'] = df['Тип подачи топлива'].map({
    'карбюратор': 0,
    'инжектор': 1
})

df

,Стоимость,Модель,Город,Пробег,Объём двигателя,Тип топлива,Тип подачи топлива,Возраст мотоцикла,Коробка (код),Тактность (код),Подача топлива (код)
0,86,Cobra Crossfire,Уфа,10.0,150,бензин,карбюратор,12,0,1,0
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,бензин,NaN,34,NaN,1,NaN
2,6500,Днепр 16М,Барабинск,NaN,450,NaN,карбюратор,40,0,NaN,0
3,8000,Восход Восход,Кызыл,NaN,175,NaN,NaN,44,NaN,NaN,NaN
4,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,бензин,NaN,26,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,бензин,NaN,1,NaN,1,NaN
15454,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,бензин,инжектор,0,0,1,1
15455,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,бензин,NaN,2,NaN,1,NaN
15456,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,бензин,инжектор,2,0,1,1
15457,10500000,Ducati Diavel,Москва,0.0,1158,бензин,инжектор,1,0,1,1

In [110]:
df.drop(columns=['Тип подачи топлива'], inplace=True)

df

,Стоимость,Модель,Город,Пробег,Объём двигателя,Тип топлива,Возраст мотоцикла,Коробка (код),Тактность (код),Подача топлива (код)
0,86,Cobra Crossfire,Уфа,10.0,150,бензин,12,0,1,0
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,бензин,34,NaN,1,NaN
2,6500,Днепр 16М,Барабинск,NaN,450,NaN,40,0,NaN,0
3,8000,Восход Восход,Кызыл,NaN,175,NaN,44,NaN,NaN,NaN
4,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,бензин,26,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,бензин,1,NaN,1,NaN
15454,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,бензин,0,0,1,1
15455,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,бензин,2,NaN,1,NaN
15456,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,бензин,2,0,1,1
15457,10500000,Ducati Diavel,Москва,0.0,1158,бензин,1,0,1,1

In [111]:
df = pd.get_dummies(df, columns=['Тип топлива'], prefix='Топливо', dtype=int)

df

,Стоимость,Модель,Город,Пробег,Объём двигателя,Возраст мотоцикла,Коробка (код),Тактность (код),Подача топлива (код),Топливо_бензин,Топливо_газ,Топливо_дизель,Топливо_электро
0,86,Cobra Crossfire,Уфа,10.0,150,12,0,1,0,1,0,0,0
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,34,NaN,1,NaN,1,0,0,0
2,6500,Днепр 16М,Барабинск,NaN,450,40,0,NaN,0,0,0,0,0
3,8000,Восход Восход,Кызыл,NaN,175,44,NaN,NaN,NaN,0,0,0,0
4,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,26,NaN,1,NaN,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,1,NaN,1,NaN,1,0,0,0
15454,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,0,0,1,1,1,0,0,0
15455,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,2,NaN,1,NaN,1,0,0,0
15456,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,2,0,1,1,1,0,0,0
15457,10500000,Ducati Diavel,Москва,0.0,1158,1,0,1,1,1,0,0,0

In [112]:
import pandas as pd

moscow_region = {
    'Апрелевка', 'Балашиха', 'Белоозёрский', 'Бронницы', 'Верея', 'Видное', 'Волоколамск', 'Воскресенск', 'Высоковск',
    'Голицыно', 'Дедовск', 'Дзержинский', 'Дмитров', 'Долгопрудный', 'Домодедово', 'Дрезна', 'Дубна', 'Егорьевск',
    'Жуковский', 'Зарайск', 'Звенигород', 'Ивантеевка', 'Истра', 'Кашира', 'Клин', 'Коломна', 'Королёв', 'Котельники',
    'Красноармейск', 'Красногорск', 'Краснозаводск', 'Краснознаменск', 'Кубинка', 'Куровское', 'Ликино-Дулёво', 'Лобня',
    'Лосино-Петровский', 'Луховицы', 'Лыткарино', 'Люберцы', 'Можайск', 'Мытищи', 'Наро-Фоминск', 'Ногинск', 'Одинцово',
    'Озёры', 'Орехово-Зуево', 'Павловский Посад', 'Пересвет', 'Подольск', 'Протвино', 'Пушкино', 'Пущино', 'Раменское',
    'Реутов', 'Рошаль', 'Руза', 'Сергиев Посад', 'Серпухов', 'Солнечногорск', 'Старая Купавна', 'Ступино', 'Талдом',
    'Фрязино', 'Химки', 'Хотьково', 'Черноголовка', 'Чехов', 'Шатура', 'Щёлково', 'Электрогорск', 'Электросталь',
    'Электроугли', 'Яхрома', 'Андреевка', 'Аничково', 'Ашукино', 'Белоомут', 'Боброво', 'Богородское', 'Большие Вязёмы',
    'Большие Дворы', 'Бутово', 'Быково', 'ВНИИССОК', 'Вербилки', 'Власиха', 'Восход', 'Голубое', 'Горки Ленинские',
    'Деденево', 'Дрожжино', 'Жилёво', 'Жилино-1', 'Загорянский', 'Запрудня', 'Заречье', 'Звёздный городок',
    'Зеленоградский', 'Измайлово', 'Икша', 'Ильинский', 'Калининец', 'Красково', 'Кратово', 'Крюково', 'Лесной',
    'Лесной Городок', 'Лопатино', 'Лотошино', 'Малаховка', 'Малино', 'Марусино', 'Менделеево', 'Мирный', 'Мисайлово',
    'Михнево', 'Мишеронский', 'Молодёжный', 'Молоково', 'Монино', 'Нахабино', 'Некрасовский', 'Новодрожжино',
    'Новоивановское', 'Обухово', 'Октябрьский', 'Отрадное', 'Поварово', 'Биокомбината', 'им. Воровского',
    'им. Цюрупы', 'Правдинский', 'Путилково', 'Радумля', 'Решетниково', 'Ржавки', 'Родники', 'Рязановский', 'Сабурово',
    'Свердловский', 'Северный', 'Селятино', 'Серебряные Пруды', 'Скоропусковский', 'Снегири', 'Софрино',
    'Старый Городок', 'Столбовая', 'Сычёво', 'Томилино', 'Троицкое', 'Тучково', 'Уваровка', 'Удельная', 'Фосфоритный',
    'Фряново', 'Хорлово', 'Чашниково', 'Черкизово', 'Черусти', 'Шаховская'
}

leningrad_region = {
    'Бокситогорск', 'Бугры', 'Волосово', 'Волхов', 'Всеволожск', 'Выборг', 'Высоцк', 'Гатчина', 'Ивангород',
    'Каменногорск', 'Кингисепп', 'Кириши', 'Кировск', 'Колтуши', 'Коммунар', 'Кудрово', 'Лодейное Поле', 'Луга',
    'Любань', 'Мурино', 'Никольское', 'Новая Ладога', 'Отрадное', 'Пикалёво', 'Подпорожье', 'Приморск', 'Приозерск',
    'Светогорск', 'Сертолово', 'Сланцы', 'Сосновый Бор', 'Сясьстрой', 'Тельмана', 'Тихвин', 'Тосно', 'Шлиссельбург',
    'Большая Ижора', 'Будогощь', 'Важины', 'Виллози', 'Вознесенье', 'Вырица', 'Дружная Горка', 'Дубровка',
    'Ефимовский', 'имени Морозова', 'имени Свердлова', 'Красный Бор', 'Кузнечное', 'Кузьмоловский', 'Лебяжье',
    'Лесогорский', 'Мга', 'Назия', 'Никольский', 'Новоселье', 'Павлово', 'Приладожский', 'Рахья', 'Рощино', 'Рябово',
    'Свирьстрой', 'Сиверский', 'Синявино', 'Советский', 'Тайцы', 'Токсово', 'Толмачёво', 'Ульяновка', 'Фёдоровское',
    'Форносово', 'Янино-1'
}

million_cities = {
    'Новосибирск', 'Екатеринбург', 'Казань', 'Красноярск', 'Нижний Новгород', 'Челябинск', 'Уфа',
    'Краснодар', 'Самара', 'Ростов-на-Дону', 'Омск', 'Воронеж', 'Пермь', 'Волгоград'
}

def categorize_city(city):
    if city == 'Москва':
        return 'Москва'
    elif city == 'Санкт-Петербург':
        return 'Санкт-Петербург'
    elif city in moscow_region:
        return 'Московская область'
    elif city in leningrad_region:
        return 'Ленинградская область'
    elif city in million_cities:
        return 'Прочие города миллионники'
    else:
        return 'Другое'

df['Категория города'] = df['Город'].apply(categorize_city)

df = pd.get_dummies(df, columns=['Категория города'], prefix='Город', dtype=int)

df

,Стоимость,Модель,Город,Пробег,Объём двигателя,Возраст мотоцикла,Коробка (код),Тактность (код),Подача топлива (код),Топливо_бензин,Топливо_газ,Топливо_дизель,Топливо_электро,Город_Другое,Город_Ленинградская область,Город_Москва,Город_Московская область,Город_Прочие города миллионники,Город_Санкт-Петербург
0,86,Cobra Crossfire,Уфа,10.0,150,12,0,1,0,1,0,0,0,0,0,0,0,1,0
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,34,NaN,1,NaN,1,0,0,0,1,0,0,0,0,0
2,6500,Днепр 16М,Барабинск,NaN,450,40,0,NaN,0,0,0,0,0,1,0,0,0,0,0
3,8000,Восход Восход,Кызыл,NaN,175,44,NaN,NaN,NaN,0,0,0,0,1,0,0,0,0,0
4,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,26,NaN,1,NaN,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15453,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,1,NaN,1,NaN,1,0,0,0,0,0,0,0,1,0
15454,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,0,0,1,1,1,0,0,0,0,0,0,0,1,0
15455,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,2,NaN,1,NaN,1,0,0,0,0,0,0,0,1,0
15456,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,2,0,1,1,1,0,0,0,0,0,0,0,1,0
15457,10500000,Ducati Diavel,Москва,0.0,1158,1,0,1,1,1,0,0,0,0,0,1,0,0,0

In [113]:
import re

df['Модель_clean'] = (
    df['Модель'].astype(str)
    .str.lower()
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

df_filtered = df[~df['Модель_clean'].str.match(r'^(.+)\s+\1$', na=False)]

df_filtered = df_filtered.drop(columns=['Модель_clean'])

df_filtered = df_filtered.reset_index(drop=True)

df_filtered

,Стоимость,Модель,Город,Пробег,Объём двигателя,Возраст мотоцикла,Коробка (код),Тактность (код),Подача топлива (код),Топливо_бензин,Топливо_газ,Топливо_дизель,Топливо_электро,Город_Другое,Город_Ленинградская область,Город_Москва,Город_Московская область,Город_Прочие города миллионники,Город_Санкт-Петербург
0,86,Cobra Crossfire,Уфа,10.0,150,12,0,1,0,1,0,0,0,0,0,0,0,1,0
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,34,NaN,1,NaN,1,0,0,0,1,0,0,0,0,0
2,6500,Днепр 16М,Барабинск,NaN,450,40,0,NaN,0,0,0,0,0,1,0,0,0,0,0
3,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,26,NaN,1,NaN,1,0,0,0,1,0,0,0,0,0
4,10000,Иж Планета 3,Красный Чикой,NaN,350,59,0,0,0,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14827,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,1,NaN,1,NaN,1,0,0,0,0,0,0,0,1,0
14828,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,0,0,1,1,1,0,0,0,0,0,0,0,1,0
14829,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,2,NaN,1,NaN,1,0,0,0,0,0,0,0,1,0
14830,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,2,0,1,1,1,0,0,0,0,0,0,0,1,0
14831,10500000,Ducati Diavel,Москва,0.0,1158,1,0,1,1,1,0,0,0,0,0,1,0,0,0

In [114]:
def extract_brand(model):
    model = str(model).lower()
    if model.startswith("mv agusta"):
        return "MV Agusta"
    elif model.startswith("royal enfield"):
        return "Royal Enfield"
    elif model.startswith("harley-davidson"):
        return "Harley-Davidson"
    elif model.startswith("cfmoto"):
        return "CFMoto"
    else:
        return model.split()[0].capitalize()

df_filtered['Бренд'] = df_filtered['Модель'].apply(extract_brand)

selected_brands = {
    'Ducati', 'MV Agusta', 'Harley-Davidson', 'BMW', 'Indian',
    'Honda', 'Yamaha', 'Suzuki', 'Kawasaki', 'KTM',
    'Royal Enfield', 'CFMoto', 'Triumph', 'Benelli'
}

df_filtered['Бренд'] = df_filtered['Бренд'].apply(lambda b: b if b in selected_brands else "Другое")

df_filtered = pd.get_dummies(df_filtered, columns=['Бренд'], prefix='Бренд', dtype=int)

In [115]:
df_filtered

,Стоимость,Модель,Город,Пробег,Объём двигателя,Возраст мотоцикла,Коробка (код),Тактность (код),Подача топлива (код),Топливо_бензин,...,Бренд_Harley-Davidson,Бренд_Honda,Бренд_Indian,Бренд_Kawasaki,Бренд_MV Agusta,Бренд_Royal Enfield,Бренд_Suzuki,Бренд_Triumph,Бренд_Yamaha,Бренд_Другое
0,86,Cobra Crossfire,Уфа,10.0,150,12,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
1,6000,Урал ИМЗ 8.103-10,Пограничный,10.0,499,34,NaN,1,NaN,1,...,0,0,0,0,0,0,0,0,0,1
2,6500,Днепр 16М,Барабинск,NaN,450,40,0,NaN,0,0,...,0,0,0,0,0,0,0,0,0,1
3,9999,Honda CBR 919RR,Спасск-Дальний,50000.0,919,26,NaN,1,NaN,1,...,0,1,0,0,0,0,0,0,0,0
4,10000,Иж Планета 3,Красный Чикой,NaN,350,59,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14827,8100000,Harley-Davidson CVO Street Glide,Новосибирск,0.0,1977,1,NaN,1,NaN,1,...,1,0,0,0,0,0,0,0,0,0
14828,8250000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1977,0,0,1,1,1,...,1,0,0,0,0,0,0,0,0,0
14829,8500000,Harley-Davidson CVO Road Glide,Новосибирск,0.0,1923,2,NaN,1,NaN,1,...,1,0,0,0,0,0,0,0,0,0
14830,8500000,Harley-Davidson CVO Road Glide,Красноярск,0.0,1923,2,0,1,1,1,...,1,0,0,0,0,0,0,0,0,0
14831,10500000,Ducati Diavel,Москва,0.0,1158,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [117]:
from google.colab import files

df_filtered.to_csv("drom_cleaned.csv", index=False)
files.download("drom_cleaned.csv")